### PR TITLE
Add support of PicoScope 3000 series + MSO (16chan option)

### PR DESCRIPTION
**Pull request by bvernoux**

### CODE REVIEW

**Comment by azonenberg** [comment]
SERIES_UNKNOWN is no go. You need to define a series for the scope so we know what it is and can figure out what features are available.

Also, corresponding work is probably needed in the bridge. Someone tried to use the bridge not long ago with a 3000 series and had a bunch of trouble. Among other things, the function generator code was giving errors because there's no 3000 series backend for it. So that needs to be either disabled or implemented for 3000 series depending on whether 3000 has a func gen.

**Comment by bvernoux** [comment]
I have pushed for test:
- https://github.com/bvernoux/scopehal 
  - https://github.com/bvernoux/scopehal/commit/68a38a2e258e53568215db7d201f7df8710970f4
  - Add support of Picoscope 3000 series(including MSO option) 
- https://github.com/bvernoux/scopehal-pico-bridge
  - https://github.com/bvernoux/scopehal-pico-bridge/commit/bc20c7d95ecb4f5c625e4f0d8cbc4c973a5ef620
  -  Shall build fine only on GNU/Linux, Msys2/Mingw64 have issues to build fully with error: no matching function for call to 'max(int64_t&, long int)'... to be investigated

**Comment by bvernoux** [comment]
I confirm all work fine on my PC tested with Windows10 and Picoscope 3406DMSO (I still need to test the 16x MSO channels, I have checked 4 Analog channels works fine)

**Comment by bvernoux** [comment]
There is still an issue (was present in older glscopeclient when Picoscope3000 was basically supported before the refactoring) with the timebase which is wrong
image
Example capture
Horizontal scale is wrong expected signal is 1kHz/2Vp-p (Picoscope Probe compensation pin) here it is 2.5x faster (2.5KHz instead of 1KHz)
image

**Comment by bvernoux** [comment]
@azonenberg this PR is ready for merge

**Pull request merged**
